-- =============================================================================
-- DEPRECATED — 폐기된 옛 init 마이그레이션 (2026-06-18 격리)
-- =============================================================================
-- 정본(CANONICAL) init = 0001_init_schema.sql 이다. 본 파일은 적용하지 않는다.
--
-- 폐기 사유(실측):
--   본 파일은 0001_init_schema.sql 과 같은 테이블(users/dreams/dali_memory/...)을
--   "서로 다른 형(shape)"으로 정의해 드리프트를 일으켰다.
--     - 본(옛) 파일 : dreams.badges/emotions = text[],  dali_memory.chat_history,
--                     users.subscription_tier/xp/streak/last_checkin (schema.sql 계보, d987395)
--     - 0001(정본)  : dreams.badges/emotions = jsonb,   dali_memory.chat,
--                     user_entitlements/app_stats/dream_pattern_cache 포함 (b32efb0, 실 출시)
--   런타임 코드가 정본 형을 사용함이 증거로 확인됨:
--     - src/services/auth.js : dali_memory 에 { memories, chat } upsert (chat_history 아님)
--     - src/tabs/dream.js    : dreams 에 keywords/result/radar_data 매핑(jsonb)
--   따라서 live DB 에 실제 적용된 것은 0001 계보이며, 본 옛 init 은 폐기 대상이다.
--
-- 격리 방식(비파괴):
--   원본 SQL 은 아래에 주석으로 100% 보존(이력은 git 에도 박제). 모든 create/alter/
--   policy 문을 주석화하여 본 파일은 실행돼도 NO-OP 이다. 마이그레이션 순서상 0001 →
--   (본 파일) 로 흘러도 옛 형이 재적용되지 않는다.
--   ★ 파일을 삭제하지 않는 이유: Supabase 마이그레이션 히스토리(supabase_migrations.
--      schema_migrations) 에 이미 기록됐을 수 있어, 파일 제거는 CLI 정합 깨짐 위험.
--      DEPRECATED no-op 로 남기는 것이 안전한 격리다.
--
-- ★ 라이브 DB 에 본 파일을 적용하지 말 것. schema.sql 이 현재 정본 상태 문서다.
-- =============================================================================

-- (의도적 no-op) — 아래는 폐기된 원본 SQL 의 보존 사본(전부 주석). 실행되지 않는다.
--
-- -- 몽글몽글 Supabase DB 스키마
-- -- Supabase Dashboard → SQL Editor 에서 실행
-- --
-- -- 1. 사용자
-- create table if not exists users (
--   id uuid references auth.users primary key,
--   nickname text default '꿈탐험가',
--   created_at timestamptz default now(),
--   subscription_tier text default 'free',  -- 'free' | 'starlight'
--   subscription_expires_at timestamptz,
--   xp integer default 0,
--   streak integer default 0,
--   last_checkin date
-- );
-- --
-- -- 2. 꿈 기록
-- create table if not exists dreams (
--   id uuid primary key default gen_random_uuid(),
--   user_id uuid references users(id) on delete cascade,
--   content text not null,
--   title text,
--   badges text[],
--   emotions text[],
--   keywords text[],
--   result jsonb,         -- AI 해몽 결과 전체
--   radar_data jsonb,     -- 6축 스탯
--   created_at timestamptz default now()
-- );
-- --
-- -- 3. 해몽 사용량 (일별)
-- create table if not exists usage_daily (
--   user_id uuid references users(id) on delete cascade,
--   date date default current_date,
--   dream_count integer default 0,
--   primary key (user_id, date)
-- );
-- --
-- -- 4. 달이 메모리
-- create table if not exists dali_memory (
--   user_id uuid references users(id) on delete cascade primary key,
--   memories jsonb default '[]',
--   chat_history jsonb default '[]',
--   updated_at timestamptz default now()
-- );
-- --
-- -- 5. 이벤트 로그 (Phase 6용, 미리 생성)
-- create table if not exists events (
--   id bigint generated always as identity primary key,
--   user_id uuid references users(id) on delete set null,
--   event text not null,
--   properties jsonb default '{}',
--   created_at timestamptz default now()
-- );
-- --
-- -- RPC: 해몽 횟수 증가
-- create or replace function increment_dream_count(p_user_id uuid) ... (폐기)
-- --
-- -- RLS / 정책 / handle_new_user 트리거 ... (폐기 — 정본 0001_init_schema.sql 참조)
-- =============================================================================
-- (파일 끝 — no-op)
